import { describe, expect, it } from 'vitest';
import {
  BOQ_CATEGORIES,
  BOQ_QUALIFICATION,
  calculateBoqTotals,
  generateBoqFromProjectAssumptions,
} from '../src/boq-generator';

describe('generateBoqFromProjectAssumptions', () => {
  it('generates categorized lines with assumptions and qualification', () => {
    const r = generateBoqFromProjectAssumptions({
      builtUpAreaSqft: 1200,
      floors: 2,
      quality: 'standard',
      buildMode: 'new',
      contingencyPercent: 5,
    });

    expect(r.lines.length).toBeGreaterThan(8);
    expect(r.lines.every((l) => l.autoGenerated)).toBe(true);
    expect(r.lines.every((l) => l.assumption && l.assumption.length > 10)).toBe(true);
    expect(r.qualification).toBe(BOQ_QUALIFICATION);
    expect(r.assumptions.some((a) => a.includes('indicative planning BOQ'))).toBe(true);
    expect(r.subtotal).toBeGreaterThan(0);
    expect(r.contingencyAmount).toBeCloseTo(r.subtotal * 0.05, 0);
    expect(r.taxAmount).toBeNull();
    expect(r.grandTotal).toBeCloseTo(r.subtotal + r.contingencyAmount, 0);

    const cats = new Set(r.lines.map((l) => l.category));
    expect(cats.has('Preliminaries')).toBe(true);
    expect(cats.has('RCC')).toBe(true);
    expect(cats.has('Masonry')).toBe(true);
    for (const c of cats) {
      expect(BOQ_CATEGORIES.includes(c as (typeof BOQ_CATEGORIES)[number]) || c === 'Other').toBe(
        true,
      );
    }
  });

  it('skips excavation/RCC bulk for renovation mode', () => {
    const r = generateBoqFromProjectAssumptions({
      builtUpAreaSqft: 800,
      floors: 1,
      buildMode: 'renovation',
    });
    expect(r.lines.some((l) => l.category === 'Excavation')).toBe(false);
    expect(r.lines.some((l) => l.category === 'RCC')).toBe(false);
    expect(r.lines.some((l) => l.category === 'Masonry')).toBe(true);
  });

  it('applies tax only when explicitly enabled', () => {
    const without = generateBoqFromProjectAssumptions({
      builtUpAreaSqft: 1000,
      includeTax: false,
      taxPercent: 18,
    });
    expect(without.taxAmount).toBeNull();

    const withTax = generateBoqFromProjectAssumptions({
      builtUpAreaSqft: 1000,
      includeTax: true,
      taxPercent: 18,
      contingencyPercent: 0,
    });
    expect(withTax.taxPercent).toBe(18);
    expect(withTax.taxAmount).toBeCloseTo(withTax.subtotal * 0.18, 0);
  });
});

describe('calculateBoqTotals', () => {
  it('recalculates editable lines and category subtotals', () => {
    const r = calculateBoqTotals({
      title: 'Manual BOQ',
      currency: 'INR',
      contingencyPercent: 10,
      lines: [
        {
          id: '1',
          category: 'Masonry',
          item: 'Brickwork',
          unit: 'm2',
          quantity: 100,
          rate: 850,
        },
        {
          id: '2',
          category: 'Painting',
          item: 'Paint',
          unit: 'm2',
          quantity: 200,
          rate: 22,
          autoGenerated: true,
          assumption: 'manual override of generated qty',
        },
      ],
    });

    expect(r.lines[0]!.amount).toBe(85000);
    expect(r.lines[1]!.amount).toBe(4400);
    expect(r.subtotal).toBe(89400);
    expect(r.contingencyAmount).toBe(8940);
    expect(r.grandTotal).toBe(98340);
    expect(r.categorySubtotals.find((c) => c.category === 'Masonry')?.amount).toBe(85000);
    expect(r.qualification).toMatch(/not a professional tender/i);
  });
});
