ALTER TABLE "businesses" ADD COLUMN IF NOT EXISTS "pricing" TEXT;
ALTER TABLE "businesses" ADD COLUMN IF NOT EXISTS "certifications" JSONB;
ALTER TABLE "businesses" ADD COLUMN IF NOT EXISTS "faqs" JSONB;
