export {
  CONSTRUCTION_ANALYTICS_EVENTS,
  trackConstructionEvent,
  trackConstructionPageView,
  trackConstructionCategoryView,
  trackCalculatorStarted,
  trackCalculatorCompleted,
  trackCalculatorError,
  trackCalculatorReset,
  trackReverseCalculatorStarted,
  trackReverseCalculatorCompleted,
  trackReverseCalculatorError,
  trackCalculatorModeCompleted,
  trackCalculatorModeError,
  trackCalculationShared,
  trackCalculationSaved,
  trackCalculationAddedToProject,
  trackProjectCreated,
  trackProjectUpdated,
  trackBoqGenerated,
  trackComparisonStarted,
  trackComparisonCompleted,
  trackMaterialSelectorStarted,
  trackMaterialSelectorCompleted,
  trackMaterialSelectorResultClicked,
  trackPriceViewed,
  trackPricePositionViewed,
  trackPriceLocationChanged,
  trackSearchPerformed,
  trackSearchResultClicked,
  trackConstructionSearchNoResult,
  trackGuideClicked,
  trackSupplierClicked,
  trackWhatNextClicked,
  trackRelatedLinkClicked,
  categorizeConstructionResultRange,
  resolveConstructionLocationLevel,
  sanitizeConstructionAnalyticsMetadata,
  isConstructionCalculatorSlug,
  isConstructionAnalyticsPath,
  type ConstructionAnalyticsEvent,
  type ConstructionCalculatorCompletedMeta,
  type ConstructionLocationLevel,
  type ConstructionResultRangeCategory,
} from './analytics';

export {
  CONSTRUCTION_ROOT,
  constructionPath,
  constructionMaterialPath,
  constructionBrandPath,
  constructionGuidePath,
  constructionChecklistPath,
  constructionComparePath,
  constructionCalculatorPath,
} from './routes';

export {
  CONSTRUCTION_PAGE_DEFAULTS,
  CONSTRUCTION_PAGE_KEYS,
  type ConstructionPageKey,
  type ConstructionPageSeoDefaults,
} from './seo-pages';

export {
  CONSTRUCTION_FILTER_QUERY_KEYS,
  CONSTRUCTION_CALC_SHARE_QUERY_KEYS,
  buildConstructionBreadcrumbs,
  buildConstructionJsonLdGraph,
  buildConstructionMetadata,
  buildConstructionPageMetadata,
  constructionAbsoluteUrl,
  constructionCalculatorCanonicalPath,
  constructionCanonicalPath,
  constructionDefaultPath,
  constructionHubBreadcrumbs,
  formatConstructionLastUpdated,
  isConstructionCalculatorPath,
  isConstructionPrivatePath,
  resolveConstructionIndexing,
  type BuildConstructionMetadataInput,
  type ConstructionCrumbInput,
  type ConstructionIndexingInput,
  type ConstructionIndexingResult,
} from './seo';

/** Re-export calculation engine for web apps (source of truth: @varnarc/validation). */
export {
  runConstructionCalculation,
  convertUnit,
  applyWastage,
  roundMoney,
  roundQuantity,
  multiplyQuantityPrice,
  listSupportedUnits,
  DEFAULT_ENGINE_LIMITS,
  calculateConstructionCost,
  constructionCostInputSchema,
  LOCATION_MULTIPLIERS,
  NATIONAL_BASE_RATE_PER_SQFT,
  COST_CALC_VERSION,
  calculateRenovationCost,
  defaultRenovationWorkItems,
  RENOVATION_WORK_RATES,
  RENOVATION_CALC_VERSION,
  calculateConstructionAffordability,
  AFFORDABILITY_CALC_VERSION,
  compareConstructionScenarios,
  encodeScenarioSharePayload,
  decodeScenarioSharePayload,
  defaultScenarioConfigs,
  duplicateScenario,
  SCENARIO_COMPARE_VERSION,
  simulateConstructionCostChange,
  DEFAULT_COST_SIMULATOR_STATE,
  DEFAULT_MARKET_RATES,
  analyseConstructionCostOptimization,
  applyCostOptimizationLevers,
  suggestLeversForTarget,
} from '@varnarc/validation';
export type {
  ConstructionCostInput,
  ConstructionCostResult,
  ConstructionCostQuality,
  ConstructionCostPropertyType,
  RenovationCostInput,
  RenovationCostResult,
  RenovationWorkId,
  RenovationQuality,
  AffordabilityCostInput,
  AffordabilityCostResult,
  ScenarioConfig,
  ScenarioCompareResult,
  CostSimulatorState,
  CostSimulatorResult,
  CostOptimizationInput,
  CostOptimizationResult,
} from '@varnarc/validation';
