'use client';

import {
  DEFAULT_CONSTRUCTION_REPORT_DISCLAIMER,
  formatReportDate,
  type ConstructionCalculationReportData,
} from './types';

/**
 * Printable Construction Calculation Report.
 * Screen: visually hidden (sr-only / absolute off-flow) unless mode="preview".
 * Print: full branded layout with page-break-friendly sections.
 */
export function PrintableConstructionReport({
  data,
  mode = 'print-only',
  className,
}: {
  data: ConstructionCalculationReportData;
  mode?: 'print-only' | 'preview';
  className?: string;
}) {
  const disclaimer = data.disclaimer?.trim() || DEFAULT_CONSTRUCTION_REPORT_DISCLAIMER;
  const logoSrc = data.logoSrc || '/brand/logo.png';
  const visibility =
    mode === 'preview'
      ? 'block'
      : 'pointer-events-none absolute left-[-10000px] top-0 w-[210mm] opacity-0 print:pointer-events-auto print:relative print:left-auto print:top-auto print:w-auto print:opacity-100';

  return (
    <article
      className={`construction-print-report ${visibility} ${className ?? ''}`}
      aria-label={`${data.title} printable report`}
      data-construction-report="true"
    >
      <header className="construction-print-report__header">
        <div className="construction-print-report__brand">
          <img
            src={logoSrc}
            alt="Varnarc"
            width={48}
            height={48}
            className="construction-print-report__logo"
          />
          <div>
            <p className="construction-print-report__brand-name">Varnarc</p>
            <p className="construction-print-report__brand-tag">Construction calculation report</p>
          </div>
        </div>
        <div className="construction-print-report__meta">
          <p className="construction-print-report__date">{formatReportDate(data.generatedAt)}</p>
          {data.methodology?.versionLabel || data.calculatorSlug ? (
            <p className="construction-print-report__version">
              {data.methodology?.versionLabel
                ? `Methodology ${data.methodology.versionLabel}`
                : data.calculatorSlug}
            </p>
          ) : null}
        </div>
      </header>

      <h1 className="construction-print-report__title">{data.title}</h1>
      {data.subtitle ? (
        <p className="construction-print-report__subtitle">{data.subtitle}</p>
      ) : null}

      <ReportSection title="Inputs">
        <KvList items={data.inputs} empty="No inputs recorded." />
      </ReportSection>

      <ReportSection title="Result" avoidBreak={false}>
        <KvList items={data.results} empty="No result recorded." emphasize />
      </ReportSection>

      {data.breakdown?.length || data.breakdownRows?.length ? (
        <ReportSection title="Breakdown">
          {data.breakdownRows?.length ? (
            <table className="construction-print-report__table">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Qty</th>
                  <th>Unit</th>
                  <th>Rate</th>
                  <th>Amount</th>
                </tr>
              </thead>
              <tbody>
                {data.breakdownRows.map((row, i) => (
                  <tr key={`${row.label}-${i}`}>
                    <td>{row.label}</td>
                    <td>{row.quantity ?? '—'}</td>
                    <td>{row.unit ?? '—'}</td>
                    <td>{row.rate ?? '—'}</td>
                    <td>{row.amount ?? '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : null}
          {data.breakdown?.length ? <KvList items={data.breakdown} /> : null}
        </ReportSection>
      ) : null}

      {data.assumptions?.length ? (
        <ReportSection title="Assumptions">
          <ul className="construction-print-report__list">
            {data.assumptions.map((a) => (
              <li key={a}>{a}</li>
            ))}
          </ul>
        </ReportSection>
      ) : null}

      {data.methodology?.formula || data.methodology?.steps?.length ? (
        <ReportSection title="Methodology">
          {data.methodology.formula ? (
            <p className="construction-print-report__formula">{data.methodology.formula}</p>
          ) : null}
          {data.methodology.steps?.length ? (
            <ol className="construction-print-report__steps">
              {data.methodology.steps.map((step, i) => (
                <li key={`${i}-${step.slice(0, 24)}`}>{step}</li>
              ))}
            </ol>
          ) : null}
        </ReportSection>
      ) : null}

      <footer className="construction-print-report__disclaimer">
        <h2>Disclaimer</h2>
        <p>{disclaimer}</p>
        <p className="construction-print-report__footer-note">
          Generated by Varnarc Construction tools. No private account data is included unless you
          chose to add it to this report.
        </p>
      </footer>
    </article>
  );
}

function ReportSection({
  title,
  children,
  avoidBreak = true,
}: {
  title: string;
  children: React.ReactNode;
  avoidBreak?: boolean;
}) {
  return (
    <section
      className={`construction-print-report__section${avoidBreak ? ' construction-print-report__section--keep' : ''}`}
    >
      <h2>{title}</h2>
      {children}
    </section>
  );
}

function KvList({
  items,
  empty,
  emphasize,
}: {
  items: ConstructionCalculationReportData['inputs'];
  empty?: string;
  emphasize?: boolean;
}) {
  if (!items.length) {
    return <p className="construction-print-report__muted">{empty ?? '—'}</p>;
  }
  return (
    <dl
      className={`construction-print-report__kv${emphasize ? ' construction-print-report__kv--hero' : ''}`}
    >
      {items.map((item) => (
        <div
          key={item.id ?? `${item.label}-${item.value}`}
          className="construction-print-report__kv-row"
        >
          <dt>{item.label}</dt>
          <dd>
            {item.value}
            {item.hint ? (
              <span className="construction-print-report__hint">{item.hint}</span>
            ) : null}
          </dd>
        </div>
      ))}
    </dl>
  );
}
