import { roundMoney, roundQuantity } from '../construction-engine/money';
import { BOQ_CALC_VERSION, BOQ_DEFAULT_RATES_INR, BOQ_QUALIFICATION } from './rates';
import {
  boqGenerateFromProjectSchema,
  boqGeneratorInputSchema,
  type BoqCategorySubtotal,
  type BoqGenerateFromProjectInput,
  type BoqGeneratorInput,
  type BoqGeneratorLineResult,
  type BoqGeneratorResult,
} from './types';

function lineAmount(quantity: number, rate: number): number {
  return roundMoney(quantity * rate);
}

function summarize(
  title: string,
  currency: string,
  lines: BoqGeneratorLineResult[],
  contingencyPercent: number,
  taxPercent: number | null,
  includeTax: boolean,
  extraAssumptions: string[],
): BoqGeneratorResult {
  const byCat = new Map<string, BoqCategorySubtotal>();
  for (const line of lines) {
    const existing = byCat.get(line.category);
    if (existing) {
      existing.amount = roundMoney(existing.amount + line.amount);
      existing.lineCount += 1;
    } else {
      byCat.set(line.category, {
        category: line.category,
        amount: line.amount,
        lineCount: 1,
      });
    }
  }
  const categorySubtotals = [...byCat.values()];
  const subtotal = roundMoney(lines.reduce((s, l) => s + l.amount, 0));
  const contingencyAmount = roundMoney(subtotal * (contingencyPercent / 100));
  const taxable = subtotal + contingencyAmount;
  const taxAmount =
    includeTax && taxPercent != null && taxPercent > 0
      ? roundMoney(taxable * (taxPercent / 100))
      : null;
  const grandTotal = roundMoney(taxable + (taxAmount ?? 0));

  const assumptions = [
    ...extraAssumptions,
    ...lines
      .filter((l) => l.autoGenerated && l.assumption)
      .map((l) => `${l.item}: ${l.assumption}`),
    BOQ_QUALIFICATION,
  ];

  return {
    title,
    currency,
    lines,
    categorySubtotals,
    subtotal,
    contingencyPercent,
    contingencyAmount,
    taxPercent: includeTax && taxPercent != null ? taxPercent : null,
    taxAmount,
    grandTotal,
    assumptions,
    qualification: BOQ_QUALIFICATION,
    version: BOQ_CALC_VERSION,
  };
}

/**
 * Recalculate amounts / category subtotals / grand total from editable lines.
 */
export function calculateBoqTotals(raw: BoqGeneratorInput): BoqGeneratorResult {
  const input = boqGeneratorInputSchema.parse(raw);
  const lines: BoqGeneratorLineResult[] = input.lines.map((row) => ({
    id: row.id,
    category: row.category,
    item: row.item.trim(),
    description: row.description?.trim() || null,
    unit: row.unit,
    quantity: roundQuantity(row.quantity, 4),
    rate: roundMoney(row.rate),
    amount: lineAmount(row.quantity, row.rate),
    autoGenerated: Boolean(row.autoGenerated),
    assumption: row.assumption?.trim() || null,
    formulaKey: row.formulaKey ?? null,
  }));

  return summarize(
    input.title,
    input.currency.toUpperCase(),
    lines,
    input.contingencyPercent,
    input.taxPercent ?? null,
    input.includeTax && input.taxPercent != null,
    ['Totals recalculated from editable quantities and rates.'],
  );
}

type DraftLine = {
  id: string;
  category: string;
  item: string;
  description?: string;
  unit: string;
  quantity: number;
  rate: number;
  assumption: string;
  formulaKey: string;
};

function rateFor(item: string, quality: 'basic' | 'standard' | 'premium'): number {
  const base = BOQ_DEFAULT_RATES_INR[item] ?? 1000;
  const mult = quality === 'premium' ? 1.25 : quality === 'basic' ? 0.85 : 1;
  return roundMoney(base * mult);
}

/**
 * Generate an indicative BOQ from project size / quality assumptions.
 * Every auto line carries an assumption string; not a tender BOQ.
 */
export function generateBoqFromProjectAssumptions(
  raw: BoqGenerateFromProjectInput,
): BoqGeneratorResult {
  const input = boqGenerateFromProjectSchema.parse(raw);
  const A = input.builtUpAreaSqft;
  const plot = input.plotAreaSqft ?? A * 1.2;
  const F = input.floors;
  const q = input.quality;
  const renovation = input.buildMode === 'renovation';
  const sqftToM2 = 0.092903;
  const areaM2 = A * sqftToM2;
  const plotM2 = plot * sqftToM2;

  const drafts: DraftLine[] = [];
  const push = (line: Omit<DraftLine, 'id'>) => {
    drafts.push({ ...line, id: `auto-${drafts.length + 1}` });
  };

  push({
    category: 'Preliminaries',
    item: 'Site establishment (LS)',
    description: 'Mobilization, temporary facilities (indicative LS)',
    unit: 'lump_sum',
    quantity: 1,
    rate: rateFor('Site establishment (LS)', q),
    assumption: 'Lump-sum preliminary allowance; not measured from drawings.',
    formulaKey: 'prelim_ls',
  });

  if (!renovation) {
    const excavM3 = roundQuantity(plotM2 * 0.45, 3);
    push({
      category: 'Excavation',
      item: 'Excavation in ordinary soil',
      description: 'Indicative bulk excavation',
      unit: 'm3',
      quantity: excavM3,
      rate: rateFor('Excavation in ordinary soil', q),
      assumption: `plotAreaM2 × 0.45 m depth ≈ ${plotM2.toFixed(1)} × 0.45. Assumes ordinary soil; confirm with soil report.`,
      formulaKey: 'excav_plot_0.45',
    });

    const pccM3 = roundQuantity(areaM2 * 0.04, 3);
    push({
      category: 'PCC',
      item: 'PCC 1:4:8 under foundations',
      description: 'Lean concrete bed (indicative)',
      unit: 'm3',
      quantity: pccM3,
      rate: rateFor('PCC 1:4:8 under foundations', q),
      assumption: `builtUpAreaM2 × 0.04 ≈ ${areaM2.toFixed(1)} × 0.04. Typical lean PCC thumb rule — not a foundation design.`,
      formulaKey: 'pcc_area_0.04',
    });

    const rccM3 = roundQuantity(areaM2 * 0.12 * Math.max(1, F * 0.85), 3);
    push({
      category: 'RCC',
      item: 'RCC M20 structural concrete',
      description: 'Footings / columns / beams / slabs combined allowance',
      unit: 'm3',
      quantity: rccM3,
      rate: rateFor('RCC M20 structural concrete', q),
      assumption: `builtUpAreaM2 × 0.12 × max(1, floors×0.85). Planning thumb rule only — not structural design.`,
      formulaKey: 'rcc_area_floors',
    });

    const steelKg = roundQuantity(rccM3 * 90, 1);
    push({
      category: 'Reinforcement',
      item: 'TMT reinforcement steel',
      description: 'Indicative steel for RCC volume',
      unit: 'kg',
      quantity: steelKg,
      rate: rateFor('TMT reinforcement steel', q),
      assumption: `RCC volume × 90 kg/m³. Preliminary ratio — actual BBS must follow structural drawings.`,
      formulaKey: 'steel_rcc_90',
    });

    const formM2 = roundQuantity(areaM2 * 1.1 * F, 2);
    push({
      category: 'Formwork',
      item: 'Formwork for RCC',
      unit: 'm2',
      quantity: formM2,
      rate: rateFor('Formwork for RCC', q),
      assumption: `builtUpAreaM2 × 1.1 × floors. Contact-area thumb rule.`,
      formulaKey: 'formwork_area_floors',
    });
  }

  const masonryM2 = roundQuantity(areaM2 * (renovation ? 0.8 : 1.4), 2);
  push({
    category: 'Masonry',
    item: 'Brick masonry in CM 1:6',
    description: 'Walling allowance',
    unit: 'm2',
    quantity: masonryM2,
    rate: rateFor('Brick masonry in CM 1:6', q),
    assumption: renovation
      ? 'Renovation: builtUpAreaM2 × 0.8 walling allowance.'
      : 'New build: builtUpAreaM2 × 1.4 walling allowance.',
    formulaKey: 'masonry_area',
  });

  push({
    category: 'Plaster',
    item: 'Internal plaster 12 mm',
    unit: 'm2',
    quantity: roundQuantity(areaM2 * 2.8, 2),
    rate: rateFor('Internal plaster 12 mm', q),
    assumption: 'builtUpAreaM2 × 2.8 for wall/ceiling plaster allowance.',
    formulaKey: 'plaster_area_2.8',
  });

  push({
    category: 'Flooring',
    item: 'Flooring (vitrified / ceramic)',
    unit: 'm2',
    quantity: roundQuantity(areaM2, 2),
    rate: rateFor('Flooring (vitrified / ceramic)', q),
    assumption: 'Flooring ≈ built-up area in m² (no wastage added here — edit if needed).',
    formulaKey: 'flooring_eq_area',
  });

  push({
    category: 'Painting',
    item: 'Interior painting (2 coats)',
    unit: 'm2',
    quantity: roundQuantity(areaM2 * 2.5, 2),
    rate: rateFor('Interior painting (2 coats)', q),
    assumption: 'builtUpAreaM2 × 2.5 paint surface allowance.',
    formulaKey: 'paint_area_2.5',
  });

  if (!renovation) {
    push({
      category: 'Waterproofing',
      item: 'Terrace waterproofing',
      unit: 'm2',
      quantity: roundQuantity(areaM2 / Math.max(1, F), 2),
      rate: rateFor('Terrace waterproofing', q),
      assumption: 'Approx. builtUpAreaM2 / floors as terrace area proxy.',
      formulaKey: 'waterproof_terrace',
    });
  }

  push({
    category: 'Electrical',
    item: 'Electrical rough-in (LS)',
    unit: 'lump_sum',
    quantity: 1,
    rate: roundMoney(rateFor('Electrical rough-in (LS)', q) * (A / 1000)),
    assumption: `LS scaled by built-up/1000 sq ft (A=${A}). Provisional — not a detailed load schedule.`,
    formulaKey: 'elec_ls_scaled',
  });

  push({
    category: 'Plumbing',
    item: 'Plumbing rough-in (LS)',
    unit: 'lump_sum',
    quantity: 1,
    rate: roundMoney(rateFor('Plumbing rough-in (LS)', q) * (A / 1000)),
    assumption: `LS scaled by built-up/1000 sq ft. Provisional MEP allowance.`,
    formulaKey: 'plumb_ls_scaled',
  });

  push({
    category: 'Sanitary',
    item: 'Sanitary fittings (provisional)',
    unit: 'lump_sum',
    quantity: 1,
    rate: rateFor('Sanitary fittings (provisional)', q),
    assumption: 'Provisional LS for fittings — replace with schedule from drawings.',
    formulaKey: 'sanitary_ls',
  });

  push({
    category: 'Doors/windows',
    item: 'Doors & windows (provisional)',
    unit: 'lump_sum',
    quantity: 1,
    rate: rateFor('Doors & windows (provisional)', q),
    assumption: 'Provisional LS — replace with opening schedule.',
    formulaKey: 'openings_ls',
  });

  push({
    category: 'Carpentry',
    item: 'Carpentry / joinery (provisional)',
    unit: 'lump_sum',
    quantity: 1,
    rate: rateFor('Carpentry / joinery (provisional)', q),
    assumption: 'Provisional LS for joinery works.',
    formulaKey: 'carpentry_ls',
  });

  if (!renovation) {
    push({
      category: 'External works',
      item: 'External works / compound (LS)',
      unit: 'lump_sum',
      quantity: 1,
      rate: rateFor('External works / compound (LS)', q),
      assumption: 'Provisional external works LS.',
      formulaKey: 'external_ls',
    });
  }

  const lines: BoqGeneratorLineResult[] = drafts.map((d) => ({
    id: d.id,
    category: d.category,
    item: d.item,
    description: d.description ?? null,
    unit: d.unit,
    quantity: d.quantity,
    rate: d.rate,
    amount: lineAmount(d.quantity, d.rate),
    autoGenerated: true,
    assumption: d.assumption,
    formulaKey: d.formulaKey,
  }));

  return summarize(
    input.title ?? 'Indicative project BOQ',
    'INR',
    lines,
    input.contingencyPercent,
    input.taxPercent ?? null,
    Boolean(input.includeTax && input.taxPercent != null),
    [
      `Generated from built-up ${A} sq ft, floors ${F}, quality ${q}, mode ${input.buildMode}.`,
      plot !== A * 1.2
        ? `Plot area ${plot} sq ft used for excavation where applicable.`
        : 'Plot area defaulted to 1.2 × built-up where not provided.',
      'Unit rates are indicative defaults scaled by quality — edit before use.',
    ],
  );
}
