/** BOQ Generator types. */

import { z } from 'zod';
import { BOQ_CATEGORIES } from './rates';

export const boqCategorySchema = z.enum(BOQ_CATEGORIES);

export const boqGeneratorLineSchema = z.object({
  id: z.string().min(1).max(64),
  category: z.string().min(1).max(80),
  item: z.string().min(1).max(200),
  description: z.string().max(2000).optional().nullable(),
  unit: z.string().min(1).max(40),
  quantity: z.number().finite().min(0).max(1_000_000_000),
  rate: z.number().finite().min(0).max(50_000_000),
  /** Set when quantity came from a formula */
  autoGenerated: z.boolean().default(false),
  assumption: z.string().max(2000).optional().nullable(),
  formulaKey: z.string().max(80).optional().nullable(),
});

export const boqGeneratorInputSchema = z.object({
  title: z.string().min(1).max(150).default('Project BOQ'),
  currency: z.string().length(3).default('INR'),
  lines: z.array(boqGeneratorLineSchema).min(0).max(2000),
  /** Contingency % applied to subtotal — 0 disables */
  contingencyPercent: z.number().min(0).max(50).default(5),
  /**
   * Tax % — only applied when explicitly provided (jurisdiction configured).
   * Omit / null = do not show or add tax.
   */
  taxPercent: z.number().min(0).max(50).optional().nullable(),
  includeTax: z.boolean().default(false),
});

export const boqGenerateFromProjectSchema = z.object({
  builtUpAreaSqft: z.number().positive().max(5_000_000),
  plotAreaSqft: z.number().positive().max(5_000_000).optional().nullable(),
  floors: z.number().positive().max(100).default(1),
  quality: z.enum(['basic', 'standard', 'premium']).default('standard'),
  buildMode: z.enum(['new', 'renovation']).default('new'),
  title: z.string().min(1).max(150).optional(),
  contingencyPercent: z.number().min(0).max(50).default(5),
  taxPercent: z.number().min(0).max(50).optional().nullable(),
  includeTax: z.boolean().default(false),
});

export type BoqGeneratorLineInput = z.input<typeof boqGeneratorLineSchema>;
export type BoqGeneratorInput = z.input<typeof boqGeneratorInputSchema>;
export type BoqGenerateFromProjectInput = z.input<typeof boqGenerateFromProjectSchema>;

export type BoqGeneratorLineResult = {
  id: string;
  category: string;
  item: string;
  description: string | null;
  unit: string;
  quantity: number;
  rate: number;
  amount: number;
  autoGenerated: boolean;
  assumption: string | null;
  formulaKey: string | null;
};

export type BoqCategorySubtotal = {
  category: string;
  amount: number;
  lineCount: number;
};

export type BoqGeneratorResult = {
  title: string;
  currency: string;
  lines: BoqGeneratorLineResult[];
  categorySubtotals: BoqCategorySubtotal[];
  subtotal: number;
  contingencyPercent: number;
  contingencyAmount: number;
  taxPercent: number | null;
  taxAmount: number | null;
  grandTotal: number;
  assumptions: string[];
  qualification: string;
  version: string;
};
