'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import {
  BOQ_CALC_VERSION,
  BOQ_CATEGORIES,
  BOQ_QUALIFICATION,
  CONSTRUCTION_UNITS,
  calculateBoqTotals,
  generateBoqFromProjectAssumptions,
  type BoqGeneratorResult,
} from '@varnarc/validation';
import {
  CalculationResult,
  CalculatorShell,
  MethodologyPanel,
} from '@/components/construction/calculator';
import { ConstructionRelatedSection } from '@/components/construction/construction-related-section';
import { cn, cx } from '@/components/construction/styles';
import { wizardMeta } from '@/components/construction/project-dashboard/dashboard-metrics';
import {
  trackBoqGenerated,
  trackCalculationAddedToProject,
  trackCalculationShared,
  trackCalculatorCompleted,
  trackCalculatorError,
} from '@/lib/construction/analytics';
import { csvEscape, downloadCsv } from '@/lib/construction/export';
import { ConstructionReportActions, reportFromBoq } from '@/components/construction/report';
import {
  clearConstructionCalculationSave,
  publishConstructionCalculationSave,
} from '@/lib/construction/save-calculation/publish';
import type { ConstructionProject } from '@/services/construction';
import { BOQ_GEN_FAQS, BOQ_GEN_SEO, BOQ_GEN_WORKED_EXAMPLE } from './content';

const CALC_TYPE = 'boq_generator';

type EditableLine = {
  id: string;
  category: string;
  item: string;
  description: string;
  unit: string;
  quantity: string;
  rate: string;
  autoGenerated: boolean;
  assumption: string;
  formulaKey: string;
};

function newLine(partial?: Partial<EditableLine>): EditableLine {
  return {
    id: `boq-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    category: 'Other',
    item: '',
    description: '',
    unit: 'nos',
    quantity: '1',
    rate: '0',
    autoGenerated: false,
    assumption: '',
    formulaKey: '',
    ...partial,
  };
}

function formatInr(n: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(n);
}

function linesFromResult(result: BoqGeneratorResult): EditableLine[] {
  return result.lines.map((l) => ({
    id: l.id,
    category: l.category,
    item: l.item,
    description: l.description ?? '',
    unit: l.unit,
    quantity: String(l.quantity),
    rate: String(l.rate),
    autoGenerated: l.autoGenerated,
    assumption: l.assumption ?? '',
    formulaKey: l.formulaKey ?? '',
  }));
}

function qualityFromProject(q?: string | null): 'basic' | 'standard' | 'premium' {
  const v = (q ?? 'standard').toLowerCase();
  if (v === 'basic' || v === 'premium') return v;
  return 'standard';
}

export function BoqGeneratorClient() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const projectIdParam = searchParams.get('projectId');
  const boqIdParam = searchParams.get('boqId');

  const [title, setTitle] = useState('Indicative project BOQ');
  const [lines, setLines] = useState<EditableLine[]>([
    newLine({
      category: 'Preliminaries',
      item: 'Site establishment (LS)',
      unit: 'lump_sum',
      quantity: '1',
      rate: '25000',
    }),
  ]);
  const [contingencyPercent, setContingencyPercent] = useState('5');
  const [includeTax, setIncludeTax] = useState(false);
  const [taxPercent, setTaxPercent] = useState('');
  const [builtUp, setBuiltUp] = useState('1200');
  const [plotArea, setPlotArea] = useState('');
  const [floors, setFloors] = useState('2');
  const [quality, setQuality] = useState<'basic' | 'standard' | 'premium'>('standard');
  const [buildMode, setBuildMode] = useState<'new' | 'renovation'>('new');
  const [projectId, setProjectId] = useState<string | null>(projectIdParam);
  const [savedBoqId, setSavedBoqId] = useState<string | null>(boqIdParam);
  const [projects, setProjects] = useState<Array<{ id: string; name: string }>>([]);
  const [result, setResult] = useState<BoqGeneratorResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [actionMsg, setActionMsg] = useState<string | null>(null);
  const [saveLoading, setSaveLoading] = useState(false);
  const [loadMsg, setLoadMsg] = useState<string | null>(null);

  const units = useMemo(() => [...CONSTRUCTION_UNITS], []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch('/api/construction/projects', { cache: 'no-store' });
        if (res.status === 401 || !res.ok) return;
        const json = await res.json();
        const list = (json?.data ?? json ?? []) as ConstructionProject[];
        if (cancelled || !Array.isArray(list)) return;
        setProjects(list.map((p) => ({ id: p.id, name: p.name || 'Untitled project' })));
      } catch {
        /* ignore */
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!projectIdParam) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/construction/projects/${projectIdParam}`, {
          cache: 'no-store',
        });
        if (!res.ok) return;
        const json = await res.json();
        const project = (json?.data ?? json) as ConstructionProject;
        if (cancelled || !project?.id) return;
        setProjectId(project.id);
        setTitle(`${project.name || 'Project'} — indicative BOQ`);
        const meta = wizardMeta(project);
        const area =
          meta?.builtUpAreaSqft ?? (project.areaSqft != null ? Number(project.areaSqft) : null);
        if (area && area > 0) setBuiltUp(String(area));
        if (meta?.plotAreaSqft) setPlotArea(String(meta.plotAreaSqft));
        if (meta?.floors) setFloors(String(meta.floors));
        if (meta?.buildMode === 'renovation' || meta?.buildMode === 'new') {
          setBuildMode(meta.buildMode);
        }
        setQuality(qualityFromProject(project.quality));
        setLoadMsg(
          `Loaded assumptions from project “${project.name}”. Generate to apply formulas.`,
        );
      } catch {
        /* ignore */
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [projectIdParam]);

  useEffect(() => {
    if (!boqIdParam) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/construction/boqs/${boqIdParam}`, { cache: 'no-store' });
        if (!res.ok) return;
        const json = await res.json();
        const boq = json?.data ?? json;
        if (cancelled || !boq?.id) return;
        setSavedBoqId(boq.id);
        setProjectId(boq.projectId ?? projectIdParam);
        setTitle(boq.name || 'Saved BOQ');
        const items = (boq.items ?? []) as Array<{
          id: string;
          name: string;
          description?: string | null;
          unit: string;
          quantity: number | string;
          unitRate: number | string;
          metadata?: {
            category?: string;
            autoGenerated?: boolean;
            assumption?: string;
            formulaKey?: string;
          } | null;
        }>;
        if (items.length) {
          setLines(
            items.map((item, i) =>
              newLine({
                id: item.id || `loaded-${i}`,
                category: item.metadata?.category || 'Other',
                item: item.name,
                description: item.description ?? '',
                unit: item.unit,
                quantity: String(item.quantity),
                rate: String(item.unitRate),
                autoGenerated: Boolean(item.metadata?.autoGenerated),
                assumption: item.metadata?.assumption ?? '',
                formulaKey: item.metadata?.formulaKey ?? '',
              }),
            ),
          );
        }
        const notes = String(boq.notes ?? '');
        const cont = notes.match(/contingencyPercent=([\d.]+)/);
        const tax = notes.match(/taxPercent=([\d.]+)/);
        if (cont) setContingencyPercent(cont[1]!);
        if (tax) {
          setIncludeTax(true);
          setTaxPercent(tax[1]!);
        }
        setLoadMsg('Loaded saved BOQ — edit quantities and rates as needed.');
      } catch {
        /* ignore */
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [boqIdParam, projectIdParam]);

  function updateLine(id: string, patch: Partial<EditableLine>) {
    setLines((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  }

  function addLine(category?: string) {
    setLines((prev) => [...prev, newLine(category ? { category } : undefined)]);
  }

  function duplicateLine(id: string) {
    setLines((prev) => {
      const idx = prev.findIndex((r) => r.id === id);
      if (idx < 0) return prev;
      const source = prev[idx]!;
      const copy = newLine({
        ...source,
        id: undefined,
        item: `${source.item} (copy)`,
        autoGenerated: false,
        assumption: source.assumption
          ? `Duplicated from auto line. Original assumption: ${source.assumption}`
          : '',
        formulaKey: '',
      });
      const next = [...prev];
      next.splice(idx + 1, 0, copy);
      return next;
    });
  }

  function removeLine(id: string) {
    setLines((prev) => (prev.length <= 1 ? prev : prev.filter((r) => r.id !== id)));
  }

  function computeTotals(sourceLines = lines): BoqGeneratorResult | null {
    try {
      return calculateBoqTotals({
        title: title.trim() || 'Project BOQ',
        currency: 'INR',
        contingencyPercent: Number(contingencyPercent) || 0,
        includeTax,
        taxPercent: includeTax && taxPercent.trim() ? Number(taxPercent) : null,
        lines: sourceLines.map((r) => ({
          id: r.id,
          category: r.category,
          item: r.item.trim() || 'Untitled item',
          description: r.description.trim() || null,
          unit: r.unit,
          quantity: Number(r.quantity) || 0,
          rate: Number(r.rate) || 0,
          autoGenerated: r.autoGenerated,
          assumption: r.assumption.trim() || null,
          formulaKey: r.formulaKey || null,
        })),
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not calculate BOQ');
      return null;
    }
  }

  function runRecalc(e?: React.FormEvent) {
    e?.preventDefault();
    setError(null);
    setActionMsg(null);
    const next = computeTotals();
    if (!next) {
      trackCalculatorError({
        calculator_type: CALC_TYPE,
        error_code: 'calc_failed',
        logged_in: false,
      });
      setResult(null);
      clearConstructionCalculationSave();
      return;
    }
    setResult(next);
    publishConstructionCalculationSave({
      calculatorSlug: 'boq-generator',
      methodologyVersionLabel: next.version ?? BOQ_CALC_VERSION,
      inputs: { title, contingencyPercent, includeTax, taxPercent, lines },
      normalizedInputs: {
        title: title.trim() || 'Project BOQ',
        currency: 'INR',
        contingencyPercent: Number(contingencyPercent) || 0,
        includeTax,
        taxPercent: includeTax && taxPercent.trim() ? Number(taxPercent) : null,
        lines,
      },
      outputs: next,
      assumptions: next.assumptions ?? null,
      sourcePath: '/construction/boq-generator',
    });
    trackCalculatorCompleted({
      calculator_type: CALC_TYPE,
      unit: 'INR',
      result_range_category:
        next.grandTotal <= 500_000 ? 'low' : next.grandTotal <= 5_000_000 ? 'mid' : 'high',
      logged_in: Boolean(projectId),
    });
  }

  function generateFromAssumptions() {
    setError(null);
    setActionMsg(null);
    try {
      const generated = generateBoqFromProjectAssumptions({
        builtUpAreaSqft: Number(builtUp),
        plotAreaSqft: plotArea.trim() ? Number(plotArea) : null,
        floors: Number(floors) || 1,
        quality,
        buildMode,
        title: title.trim() || 'Indicative project BOQ',
        contingencyPercent: Number(contingencyPercent) || 0,
        includeTax,
        taxPercent: includeTax && taxPercent.trim() ? Number(taxPercent) : null,
      });
      setLines(linesFromResult(generated));
      setResult(generated);
      setActionMsg('Generated indicative lines from assumptions. Review every auto quantity.');
      trackBoqGenerated({
        logged_in: Boolean(projectId),
        item_count_bucket: generated.lines.length <= 10 ? 'few' : 'many',
      });
      trackCalculatorCompleted({
        calculator_type: CALC_TYPE,
        unit: 'INR',
        result_range_category: 'mid',
        logged_in: Boolean(projectId),
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed');
      trackCalculatorError({
        calculator_type: CALC_TYPE,
        error_code: 'generate_failed',
        logged_in: false,
      });
    }
  }

  function duplicateBoqDocument() {
    setTitle((t) => `${t.replace(/\s*\(copy\)\s*$/i, '')} (copy)`);
    setSavedBoqId(null);
    setLines((prev) =>
      prev.map((l) =>
        newLine({
          ...l,
          id: undefined,
          autoGenerated: false,
          assumption: l.assumption
            ? `Duplicated document. ${l.assumption}`
            : l.autoGenerated
              ? 'Duplicated from a previously generated line.'
              : '',
        }),
      ),
    );
    setResult(null);
    setActionMsg('Duplicated BOQ in the editor. Save to create a new project version.');
  }

  function exportSpreadsheet() {
    const next = result ?? computeTotals();
    if (!next) return;
    setResult(next);
    const linesCsv = [
      'Category,Item,Description,Unit,Quantity,Rate,Amount,Auto_generated,Assumption',
      ...next.lines.map((r) =>
        [
          csvEscape(r.category),
          csvEscape(r.item),
          csvEscape(r.description),
          csvEscape(r.unit),
          r.quantity,
          r.rate,
          r.amount,
          r.autoGenerated ? 'yes' : 'no',
          csvEscape(r.assumption),
        ].join(','),
      ),
      '',
      'Category_subtotals,Amount,Line_count',
      ...next.categorySubtotals.map((c) => `${csvEscape(c.category)},${c.amount},${c.lineCount}`),
      '',
      `Subtotal,,,${next.subtotal}`,
      `Contingency_${next.contingencyPercent}%,,,${next.contingencyAmount}`,
      next.taxAmount != null ? `Tax_${next.taxPercent}%,,,${next.taxAmount}` : '',
      `Grand_total,,,${next.grandTotal}`,
      `NOTE,${csvEscape(BOQ_QUALIFICATION)}`,
    ].filter(Boolean);
    downloadCsv('varnarc-indicative-boq.csv', linesCsv);
    trackBoqGenerated({
      logged_in: Boolean(projectId),
      item_count_bucket: next.lines.length <= 10 ? 'few' : 'many',
    });
    setActionMsg('Spreadsheet (CSV) downloaded.');
  }

  async function shareBoq() {
    const next = result ?? computeTotals();
    if (!next) return;
    const text = `Varnarc indicative planning BOQ: ${next.lines.length} items, grand total ${formatInr(next.grandTotal)}. ${BOQ_QUALIFICATION}`;
    try {
      if (navigator.share) {
        await navigator.share({ title: next.title, text, url: window.location.href });
      } else {
        await navigator.clipboard.writeText(`${text}\n${window.location.href}`);
        setActionMsg('Copied BOQ summary to clipboard.');
      }
      trackCalculationShared({ calculator_type: CALC_TYPE });
    } catch {
      setActionMsg('Could not share — copy the URL manually.');
    }
  }

  async function saveToProject() {
    if (!projectId) {
      setActionMsg('Choose a saved project (or open with ?projectId=) to save this BOQ.');
      return;
    }
    const next = result ?? computeTotals();
    if (!next || next.lines.length === 0) {
      setActionMsg('Add at least one line before saving.');
      return;
    }
    setSaveLoading(true);
    setActionMsg(null);
    try {
      const res = await fetch(`/api/construction/projects/${projectId}/boqs`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: next.title.slice(0, 150),
          currency: 'INR',
          status: 'DRAFT',
          contingencyPercent: next.contingencyPercent,
          taxPercent: next.taxPercent,
          notes: BOQ_QUALIFICATION,
          items: next.lines.map((l, index) => {
            const descParts = [l.description, l.assumption ? `Assumption: ${l.assumption}` : null]
              .filter(Boolean)
              .join(' | ');
            return {
              name: l.item,
              description: descParts ? descParts.slice(0, 2000) : null,
              unit: l.unit,
              quantity: l.quantity,
              unitRate: l.rate,
              sortOrder: index,
              metadata: {
                category: l.category,
                autoGenerated: l.autoGenerated,
                assumption: l.assumption,
                formulaKey: l.formulaKey,
              },
            };
          }),
        }),
      });
      if (res.status === 401) {
        setActionMsg('Sign in to save this BOQ to a project.');
        return;
      }
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body?.error?.message || 'Save failed');
      }
      const json = await res.json();
      const saved = json?.data ?? json;
      setSavedBoqId(saved?.id ?? null);
      setResult(next);
      setActionMsg('BOQ saved to project.');
      trackCalculationAddedToProject({ calculator_type: CALC_TYPE, logged_in: true });
      trackBoqGenerated({
        logged_in: true,
        item_count_bucket: next.lines.length <= 10 ? 'few' : 'many',
      });
      router.push(`/construction/project/${projectId}?tab=boq`);
    } catch (err) {
      setActionMsg(err instanceof Error ? err.message : 'Save failed');
    } finally {
      setSaveLoading(false);
    }
  }

  async function downloadPdf() {
    if (!savedBoqId) {
      setActionMsg('Save the BOQ to a project first, then download PDF.');
      return;
    }
    try {
      const res = await fetch(`/api/construction/boqs/${savedBoqId}/report-pdf`, {
        cache: 'no-store',
      });
      if (res.status === 401) {
        setActionMsg('Sign in to download the PDF.');
        return;
      }
      if (!res.ok) throw new Error('PDF download failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'varnarc-indicative-boq.pdf';
      a.click();
      URL.revokeObjectURL(url);
      setActionMsg('PDF downloaded (indicative planning BOQ).');
    } catch (err) {
      setActionMsg(err instanceof Error ? err.message : 'PDF download failed');
    }
  }

  async function duplicateSavedBoq() {
    if (!savedBoqId) {
      duplicateBoqDocument();
      return;
    }
    setSaveLoading(true);
    try {
      const res = await fetch(`/api/construction/boqs/${savedBoqId}/duplicate`, {
        method: 'POST',
      });
      if (res.status === 401) {
        setActionMsg('Sign in to duplicate a saved BOQ.');
        return;
      }
      if (!res.ok) throw new Error('Duplicate failed');
      const json = await res.json();
      const copy = json?.data ?? json;
      setSavedBoqId(copy?.id ?? null);
      setActionMsg(`Duplicated as v${copy?.version ?? '?'}.`);
      if (projectId) router.push(`/construction/project/${projectId}?tab=boq`);
    } catch (err) {
      setActionMsg(err instanceof Error ? err.message : 'Duplicate failed');
    } finally {
      setSaveLoading(false);
    }
  }

  const formNode = (
    <form className={cn(cx.card, 'space-y-4 p-4 sm:p-5')} onSubmit={runRecalc}>
      <aside className="rounded-xl border border-amber-200 bg-amber-50 p-3 sm:p-4">
        <p className="text-sm font-semibold text-[#0b1f3a]">Indicative planning BOQ</p>
        <p className="mt-1 text-sm text-slate-700">{BOQ_QUALIFICATION}</p>
      </aside>

      {loadMsg ? <p className="text-sm text-slate-600">{loadMsg}</p> : null}

      <div className="grid gap-3 sm:grid-cols-2">
        <label className="block text-sm sm:col-span-2">
          <span className="mb-1 block font-medium text-slate-700">BOQ title</span>
          <input className={cx.input} value={title} onChange={(e) => setTitle(e.target.value)} />
        </label>
        <label className="block text-sm">
          <span className="mb-1 block font-medium text-slate-700">Save to project</span>
          <select
            className={cx.input}
            value={projectId ?? ''}
            onChange={(e) => setProjectId(e.target.value || null)}
          >
            <option value="">Select project…</option>
            {projects.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name}
              </option>
            ))}
          </select>
        </label>
        <div className="flex items-end">
          <Link
            href="/construction/project/new"
            className="text-sm font-medium text-[#f97316] hover:underline"
          >
            Create a project
          </Link>
        </div>
      </div>

      <fieldset className="space-y-3 rounded-xl border border-slate-200 p-3 sm:p-4">
        <legend className="px-1 text-sm font-semibold text-[#0b1f3a]">
          Generate from project assumptions
        </legend>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <label className="block text-sm">
            <span className="mb-1 block font-medium text-slate-700">Built-up (sq ft)</span>
            <input
              className={cx.input}
              type="number"
              min={1}
              value={builtUp}
              onChange={(e) => setBuiltUp(e.target.value)}
            />
          </label>
          <label className="block text-sm">
            <span className="mb-1 block font-medium text-slate-700">Plot (sq ft, optional)</span>
            <input
              className={cx.input}
              type="number"
              min={1}
              value={plotArea}
              onChange={(e) => setPlotArea(e.target.value)}
            />
          </label>
          <label className="block text-sm">
            <span className="mb-1 block font-medium text-slate-700">Floors</span>
            <input
              className={cx.input}
              type="number"
              min={1}
              value={floors}
              onChange={(e) => setFloors(e.target.value)}
            />
          </label>
          <label className="block text-sm">
            <span className="mb-1 block font-medium text-slate-700">Quality</span>
            <select
              className={cx.input}
              value={quality}
              onChange={(e) => setQuality(e.target.value as typeof quality)}
            >
              <option value="basic">Basic</option>
              <option value="standard">Standard</option>
              <option value="premium">Premium</option>
            </select>
          </label>
          <label className="block text-sm">
            <span className="mb-1 block font-medium text-slate-700">Build mode</span>
            <select
              className={cx.input}
              value={buildMode}
              onChange={(e) => setBuildMode(e.target.value as typeof buildMode)}
            >
              <option value="new">New construction</option>
              <option value="renovation">Renovation</option>
            </select>
          </label>
        </div>
        <button type="button" className={cx.secondaryBtn} onClick={generateFromAssumptions}>
          Generate indicative BOQ
        </button>
      </fieldset>

      <div className="grid gap-3 sm:grid-cols-3">
        <label className="block text-sm">
          <span className="mb-1 block font-medium text-slate-700">Contingency %</span>
          <input
            className={cx.input}
            type="number"
            min={0}
            max={50}
            value={contingencyPercent}
            onChange={(e) => setContingencyPercent(e.target.value)}
          />
        </label>
        <label className="flex items-end gap-2 pb-2 text-sm">
          <input
            type="checkbox"
            checked={includeTax}
            onChange={(e) => setIncludeTax(e.target.checked)}
          />
          <span className="font-medium text-slate-700">Include tax (jurisdiction set)</span>
        </label>
        {includeTax ? (
          <label className="block text-sm">
            <span className="mb-1 block font-medium text-slate-700">Tax %</span>
            <input
              className={cx.input}
              type="number"
              min={0}
              max={50}
              value={taxPercent}
              onChange={(e) => setTaxPercent(e.target.value)}
            />
          </label>
        ) : (
          <p className="self-end text-xs text-slate-500">Tax fields hidden until enabled.</p>
        )}
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-[960px] w-full border-collapse text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-500">
              <th className="py-2 pr-2">Category</th>
              <th className="py-2 pr-2">Item</th>
              <th className="py-2 pr-2">Description</th>
              <th className="py-2 pr-2">Unit</th>
              <th className="py-2 pr-2">Qty</th>
              <th className="py-2 pr-2">Rate</th>
              <th className="py-2 pr-2">Amount</th>
              <th className="py-2"> </th>
            </tr>
          </thead>
          <tbody>
            {lines.map((row) => {
              const amount = (Number(row.quantity) || 0) * (Number(row.rate) || 0);
              return (
                <tr key={row.id} className="border-b border-slate-100 align-top">
                  <td className="py-2 pr-2">
                    <select
                      className={cx.input}
                      value={row.category}
                      onChange={(e) => updateLine(row.id, { category: e.target.value })}
                    >
                      {BOQ_CATEGORIES.map((c) => (
                        <option key={c} value={c}>
                          {c}
                        </option>
                      ))}
                    </select>
                  </td>
                  <td className="py-2 pr-2">
                    <input
                      className={cx.input}
                      value={row.item}
                      onChange={(e) => updateLine(row.id, { item: e.target.value })}
                    />
                    {row.autoGenerated && row.assumption ? (
                      <p className="mt-1 text-xs text-slate-500">Assumption: {row.assumption}</p>
                    ) : null}
                  </td>
                  <td className="py-2 pr-2">
                    <input
                      className={cx.input}
                      value={row.description}
                      onChange={(e) => updateLine(row.id, { description: e.target.value })}
                    />
                  </td>
                  <td className="py-2 pr-2">
                    <select
                      className={cx.input}
                      value={row.unit}
                      onChange={(e) => updateLine(row.id, { unit: e.target.value })}
                    >
                      {units.map((u) => (
                        <option key={u} value={u}>
                          {u}
                        </option>
                      ))}
                    </select>
                  </td>
                  <td className="py-2 pr-2">
                    <input
                      className={cx.input}
                      type="number"
                      min={0}
                      step="any"
                      value={row.quantity}
                      onChange={(e) =>
                        updateLine(row.id, {
                          quantity: e.target.value,
                          autoGenerated: false,
                        })
                      }
                    />
                  </td>
                  <td className="py-2 pr-2">
                    <input
                      className={cx.input}
                      type="number"
                      min={0}
                      step="any"
                      value={row.rate}
                      onChange={(e) => updateLine(row.id, { rate: e.target.value })}
                    />
                  </td>
                  <td className="py-2 pr-2 whitespace-nowrap tabular-nums">{formatInr(amount)}</td>
                  <td className="py-2">
                    <div className="flex flex-col gap-1">
                      <button
                        type="button"
                        className="text-xs text-[#f97316] hover:underline"
                        onClick={() => duplicateLine(row.id)}
                      >
                        Dup
                      </button>
                      <button
                        type="button"
                        className="text-xs text-slate-500 hover:underline"
                        onClick={() => removeLine(row.id)}
                      >
                        Del
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <div className="flex flex-wrap gap-2">
        <button type="button" className={cx.secondaryBtn} onClick={() => addLine()}>
          Add custom item
        </button>
        <button type="submit" className={cx.primaryBtn}>
          Recalculate totals
        </button>
      </div>

      {error ? <p className="text-sm text-red-600">{error}</p> : null}
      {actionMsg ? <p className="text-sm text-slate-600">{actionMsg}</p> : null}
    </form>
  );

  const resultNode = result ? (
    <div className="space-y-4">
      <CalculationResult
        label="Grand total (indicative)"
        value={formatInr(result.grandTotal)}
        hint={result.qualification}
        metrics={[
          { label: 'Subtotal', value: formatInr(result.subtotal) },
          {
            label: `Contingency (${result.contingencyPercent}%)`,
            value: formatInr(result.contingencyAmount),
          },
          ...(result.taxAmount != null
            ? [{ label: `Tax (${result.taxPercent}%)`, value: formatInr(result.taxAmount) }]
            : []),
          { label: 'Lines', value: String(result.lines.length) },
        ]}
      />

      <div className={cn(cx.card, 'p-4 sm:p-5')}>
        <h3 className="text-sm font-semibold text-[#0b1f3a]">Category subtotals</h3>
        <ul className="mt-3 space-y-2 text-sm">
          {result.categorySubtotals.map((c) => (
            <li key={c.category} className="flex justify-between gap-4">
              <span>
                {c.category} <span className="text-slate-500">({c.lineCount})</span>
              </span>
              <span className="tabular-nums">{formatInr(c.amount)}</span>
            </li>
          ))}
        </ul>
      </div>

      <MethodologyPanel title="Assumptions & qualifications" steps={result.assumptions} />

      <div className="flex flex-wrap gap-2 print:hidden">
        <button
          type="button"
          className={cx.primaryBtn}
          disabled={saveLoading}
          onClick={() => void saveToProject()}
        >
          {saveLoading ? 'Saving…' : 'Save to project'}
        </button>
        <button type="button" className={cx.secondaryBtn} onClick={() => void duplicateSavedBoq()}>
          Duplicate
        </button>
        <ConstructionReportActions data={reportFromBoq({ result })} label="Print report" />
        <button type="button" className={cx.secondaryBtn} onClick={() => void downloadPdf()}>
          Download PDF
        </button>
        <button type="button" className={cx.secondaryBtn} onClick={exportSpreadsheet}>
          Export spreadsheet
        </button>
        <button type="button" className={cx.secondaryBtn} onClick={() => void shareBoq()}>
          Share
        </button>
      </div>
    </div>
  ) : null;

  return (
    <>
      <CalculatorShell
        breadcrumbs={[
          { label: 'Home', href: '/' },
          { label: 'Construction', href: '/construction' },
          { label: 'BOQ Generator' },
        ]}
        title="BOQ Generator"
        description={BOQ_GEN_SEO}
        lastUpdated="Aug 2026"
        form={formNode}
        result={resultNode}
        formula={
          <div className="space-y-3 text-sm leading-relaxed text-slate-600">
            <p className="rounded-lg bg-slate-50 px-3 py-2 font-mono text-xs sm:text-sm">
              amount = quantity × rate · category subtotal = Σ amounts · grand total = subtotal +
              contingency (+ tax only if enabled)
            </p>
            <p>
              Auto-generated quantities use published thumb-rule formulas and always expose their
              assumptions. This is not a professional tender BOQ.
            </p>
          </div>
        }
        seoContent={
          <div className="space-y-4">
            <p>{BOQ_GEN_SEO}</p>
            <h3 className="text-base font-bold text-[#0b1f3a]">Worked example</h3>
            <p>{BOQ_GEN_WORKED_EXAMPLE}</p>
          </div>
        }
        faqs={BOQ_GEN_FAQS}
        stickyCta={{
          primary: { label: 'Recalculate', onClick: () => runRecalc() },
          secondary: { label: 'Export CSV', onClick: () => exportSpreadsheet() },
        }}
      />
      <div className="site-container pb-12 print:hidden">
        <ConstructionRelatedSection entityId="calc:boq" surface="boq-generator" />
      </div>
    </>
  );
}
