import type { LucideIcon } from 'lucide-react';
import {
  Calculator,
  TrendingUp,
  Percent,
  Receipt,
  Home,
  Building2,
  Paintbrush,
  Sun,
  Car,
  Fuel,
  PiggyBank,
  Zap,
  LayoutGrid,
  Box,
  Layers,
  BookOpen,
  Wallet,
  Users,
  Scale,
  Shield,
  CheckCircle2,
  CreditCard,
  Landmark,
  FileText,
  Sparkles,
  Star,
  Tag,
  MapPin,
  Search,
  type LucideProps,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  calculator: Calculator,
  trending: TrendingUp,
  percent: Percent,
  receipt: Receipt,
  home: Home,
  building: Building2,
  paint: Paintbrush,
  sun: Sun,
  car: Car,
  fuel: Fuel,
  piggy: PiggyBank,
  zap: Zap,
  grid: LayoutGrid,
  box: Box,
  layers: Layers,
  book: BookOpen,
  wallet: Wallet,
  users: Users,
  scale: Scale,
  shield: Shield,
  check: CheckCircle2,
  card: CreditCard,
  bank: Landmark,
  file: FileText,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  map: MapPin,
  search: Search,
};

export function HubIcon({ name, className, ...props }: { name: string } & LucideProps) {
  const Icon = ICON_MAP[name] ?? Calculator;
  return <Icon className={className} aria-hidden {...props} />;
}
