/** Catalog keys for Construction Intelligence seed. Not prices. */

export const INDIA_STATES = [
  { slug: 'andhra-pradesh', name: 'Andhra Pradesh' },
  { slug: 'arunachal-pradesh', name: 'Arunachal Pradesh' },
  { slug: 'assam', name: 'Assam' },
  { slug: 'bihar', name: 'Bihar' },
  { slug: 'chhattisgarh', name: 'Chhattisgarh' },
  { slug: 'goa', name: 'Goa' },
  { slug: 'gujarat', name: 'Gujarat' },
  { slug: 'haryana', name: 'Haryana' },
  { slug: 'himachal-pradesh', name: 'Himachal Pradesh' },
  { slug: 'jharkhand', name: 'Jharkhand' },
  { slug: 'karnataka', name: 'Karnataka' },
  { slug: 'kerala', name: 'Kerala' },
  { slug: 'madhya-pradesh', name: 'Madhya Pradesh' },
  { slug: 'maharashtra', name: 'Maharashtra' },
  { slug: 'manipur', name: 'Manipur' },
  { slug: 'meghalaya', name: 'Meghalaya' },
  { slug: 'mizoram', name: 'Mizoram' },
  { slug: 'nagaland', name: 'Nagaland' },
  { slug: 'odisha', name: 'Odisha' },
  { slug: 'punjab', name: 'Punjab' },
  { slug: 'rajasthan', name: 'Rajasthan' },
  { slug: 'sikkim', name: 'Sikkim' },
  { slug: 'tamil-nadu', name: 'Tamil Nadu' },
  { slug: 'telangana', name: 'Telangana' },
  { slug: 'tripura', name: 'Tripura' },
  { slug: 'uttar-pradesh', name: 'Uttar Pradesh' },
  { slug: 'uttarakhand', name: 'Uttarakhand' },
  { slug: 'west-bengal', name: 'West Bengal' },
] as const;

export const INDIA_UTS = [
  { slug: 'andaman-and-nicobar-islands', name: 'Andaman and Nicobar Islands' },
  { slug: 'chandigarh', name: 'Chandigarh' },
  {
    slug: 'dadra-and-nagar-haveli-and-daman-and-diu',
    name: 'Dadra and Nagar Haveli and Daman and Diu',
  },
  { slug: 'delhi', name: 'Delhi' },
  { slug: 'jammu-and-kashmir', name: 'Jammu and Kashmir' },
  { slug: 'ladakh', name: 'Ladakh' },
  { slug: 'lakshadweep', name: 'Lakshadweep' },
  { slug: 'puducherry', name: 'Puducherry' },
] as const;

export const MAJOR_CITIES: Array<{ slug: string; name: string; stateSlug: string }> = [
  { slug: 'bengaluru', name: 'Bengaluru', stateSlug: 'karnataka' },
  { slug: 'mysuru', name: 'Mysuru', stateSlug: 'karnataka' },
  { slug: 'mangaluru', name: 'Mangaluru', stateSlug: 'karnataka' },
  { slug: 'hubballi', name: 'Hubballi', stateSlug: 'karnataka' },
  { slug: 'belagavi', name: 'Belagavi', stateSlug: 'karnataka' },
  { slug: 'hyderabad', name: 'Hyderabad', stateSlug: 'telangana' },
  { slug: 'warangal', name: 'Warangal', stateSlug: 'telangana' },
  { slug: 'karimnagar', name: 'Karimnagar', stateSlug: 'telangana' },
  { slug: 'chennai', name: 'Chennai', stateSlug: 'tamil-nadu' },
  { slug: 'coimbatore', name: 'Coimbatore', stateSlug: 'tamil-nadu' },
  { slug: 'madurai', name: 'Madurai', stateSlug: 'tamil-nadu' },
  { slug: 'tiruchirappalli', name: 'Tiruchirappalli', stateSlug: 'tamil-nadu' },
  { slug: 'salem', name: 'Salem', stateSlug: 'tamil-nadu' },
  { slug: 'mumbai', name: 'Mumbai', stateSlug: 'maharashtra' },
  { slug: 'pune', name: 'Pune', stateSlug: 'maharashtra' },
  { slug: 'nagpur', name: 'Nagpur', stateSlug: 'maharashtra' },
  { slug: 'nashik', name: 'Nashik', stateSlug: 'maharashtra' },
  { slug: 'thane', name: 'Thane', stateSlug: 'maharashtra' },
  { slug: 'navi-mumbai', name: 'Navi Mumbai', stateSlug: 'maharashtra' },
  { slug: 'new-delhi', name: 'Delhi', stateSlug: 'delhi' },
  { slug: 'noida', name: 'Noida', stateSlug: 'uttar-pradesh' },
  { slug: 'greater-noida', name: 'Greater Noida', stateSlug: 'uttar-pradesh' },
  { slug: 'ghaziabad', name: 'Ghaziabad', stateSlug: 'uttar-pradesh' },
  { slug: 'gurugram', name: 'Gurugram', stateSlug: 'haryana' },
  { slug: 'faridabad', name: 'Faridabad', stateSlug: 'haryana' },
  { slug: 'ahmedabad', name: 'Ahmedabad', stateSlug: 'gujarat' },
  { slug: 'surat', name: 'Surat', stateSlug: 'gujarat' },
  { slug: 'vadodara', name: 'Vadodara', stateSlug: 'gujarat' },
  { slug: 'rajkot', name: 'Rajkot', stateSlug: 'gujarat' },
  { slug: 'gandhinagar', name: 'Gandhinagar', stateSlug: 'gujarat' },
  { slug: 'jaipur', name: 'Jaipur', stateSlug: 'rajasthan' },
  { slug: 'jodhpur', name: 'Jodhpur', stateSlug: 'rajasthan' },
  { slug: 'udaipur', name: 'Udaipur', stateSlug: 'rajasthan' },
  { slug: 'kota', name: 'Kota', stateSlug: 'rajasthan' },
  { slug: 'lucknow', name: 'Lucknow', stateSlug: 'uttar-pradesh' },
  { slug: 'kanpur', name: 'Kanpur', stateSlug: 'uttar-pradesh' },
  { slug: 'varanasi', name: 'Varanasi', stateSlug: 'uttar-pradesh' },
  { slug: 'agra', name: 'Agra', stateSlug: 'uttar-pradesh' },
  { slug: 'prayagraj', name: 'Prayagraj', stateSlug: 'uttar-pradesh' },
  { slug: 'kolkata', name: 'Kolkata', stateSlug: 'west-bengal' },
  { slug: 'howrah', name: 'Howrah', stateSlug: 'west-bengal' },
  { slug: 'bhubaneswar', name: 'Bhubaneswar', stateSlug: 'odisha' },
  { slug: 'cuttack', name: 'Cuttack', stateSlug: 'odisha' },
  { slug: 'patna', name: 'Patna', stateSlug: 'bihar' },
  { slug: 'gaya', name: 'Gaya', stateSlug: 'bihar' },
  { slug: 'ranchi', name: 'Ranchi', stateSlug: 'jharkhand' },
  { slug: 'jamshedpur', name: 'Jamshedpur', stateSlug: 'jharkhand' },
  { slug: 'bhopal', name: 'Bhopal', stateSlug: 'madhya-pradesh' },
  { slug: 'indore', name: 'Indore', stateSlug: 'madhya-pradesh' },
  { slug: 'gwalior', name: 'Gwalior', stateSlug: 'madhya-pradesh' },
  { slug: 'jabalpur', name: 'Jabalpur', stateSlug: 'madhya-pradesh' },
  { slug: 'raipur', name: 'Raipur', stateSlug: 'chhattisgarh' },
  { slug: 'bilaspur', name: 'Bilaspur', stateSlug: 'chhattisgarh' },
  { slug: 'kochi', name: 'Kochi', stateSlug: 'kerala' },
  { slug: 'thiruvananthapuram', name: 'Thiruvananthapuram', stateSlug: 'kerala' },
  { slug: 'kozhikode', name: 'Kozhikode', stateSlug: 'kerala' },
  { slug: 'thrissur', name: 'Thrissur', stateSlug: 'kerala' },
  { slug: 'vijayawada', name: 'Vijayawada', stateSlug: 'andhra-pradesh' },
  { slug: 'visakhapatnam', name: 'Visakhapatnam', stateSlug: 'andhra-pradesh' },
  { slug: 'guntur', name: 'Guntur', stateSlug: 'andhra-pradesh' },
  { slug: 'tirupati', name: 'Tirupati', stateSlug: 'andhra-pradesh' },
  { slug: 'chandigarh-city', name: 'Chandigarh', stateSlug: 'chandigarh' },
  { slug: 'ludhiana', name: 'Ludhiana', stateSlug: 'punjab' },
  { slug: 'amritsar', name: 'Amritsar', stateSlug: 'punjab' },
  { slug: 'jalandhar', name: 'Jalandhar', stateSlug: 'punjab' },
  { slug: 'dehradun', name: 'Dehradun', stateSlug: 'uttarakhand' },
  { slug: 'haridwar', name: 'Haridwar', stateSlug: 'uttarakhand' },
  { slug: 'guwahati', name: 'Guwahati', stateSlug: 'assam' },
  { slug: 'panaji', name: 'Panaji', stateSlug: 'goa' },
  { slug: 'srinagar', name: 'Srinagar', stateSlug: 'jammu-and-kashmir' },
  { slug: 'jammu', name: 'Jammu', stateSlug: 'jammu-and-kashmir' },
];

export const LABOUR_TRADES = [
  'general-labour',
  'unskilled-helper',
  'mason-grade-i',
  'mason-grade-ii',
  'bar-bender',
  'steel-fixer',
  'shuttering-carpenter',
  'general-carpenter',
  'furniture-carpenter',
  'electrician',
  'electrician-assistant',
  'plumber',
  'plumber-assistant',
  'painter',
  'painter-assistant',
  'tile-mason',
  'granite-mason',
  'marble-mason',
  'polisher',
  'welder',
  'fabricator',
  'gypsum-installer',
  'false-ceiling-installer',
  'waterproofing-technician',
  'glass-installer',
  'aluminium-installer',
  'upvc-installer',
  'hvac-technician',
  'solar-technician',
  'equipment-operator',
  'excavator-operator',
  'site-supervisor',
  'foreman',
  'safety-worker',
  'interior-carpenter',
  'laminate-installer',
  'pu-polish-worker',
] as const;

export const PHASE_TEMPLATES = [
  { code: 'PRE_CONSTRUCTION', name: 'Pre-construction', sortOrder: 1 },
  { code: 'SITE_PREPARATION', name: 'Site preparation', sortOrder: 2 },
  { code: 'FOUNDATION', name: 'Foundation', sortOrder: 3 },
  { code: 'PLINTH', name: 'Plinth', sortOrder: 4 },
  { code: 'RCC_STRUCTURE', name: 'RCC structure', sortOrder: 5 },
  { code: 'MASONRY', name: 'Masonry', sortOrder: 6 },
  { code: 'PLASTERING', name: 'Plastering', sortOrder: 7 },
  { code: 'WATERPROOFING', name: 'Waterproofing', sortOrder: 8 },
  { code: 'ELECTRICAL_ROUGH_IN', name: 'Electrical rough-in', sortOrder: 9 },
  { code: 'PLUMBING_ROUGH_IN', name: 'Plumbing rough-in', sortOrder: 10 },
  { code: 'FLOORING', name: 'Flooring', sortOrder: 11 },
  { code: 'WINDOWS', name: 'Windows', sortOrder: 12 },
  { code: 'DOORS', name: 'Doors', sortOrder: 13 },
  { code: 'SANITARY', name: 'Sanitary', sortOrder: 14 },
  { code: 'PAINTING', name: 'Painting', sortOrder: 15 },
  { code: 'FALSE_CEILING', name: 'False ceiling', sortOrder: 16 },
  { code: 'KITCHEN', name: 'Kitchen', sortOrder: 17 },
  { code: 'INTERIORS', name: 'Interiors', sortOrder: 18 },
  { code: 'EXTERNAL_WORK', name: 'External work', sortOrder: 19 },
  { code: 'LANDSCAPING', name: 'Landscaping', sortOrder: 20 },
  { code: 'TESTING', name: 'Testing', sortOrder: 21 },
  { code: 'CLEANING', name: 'Cleaning', sortOrder: 22 },
  { code: 'HANDOVER', name: 'Handover', sortOrder: 23 },
] as const;

export const QUALITY_TIERS = [
  { code: 'ECONOMY', name: 'Economy', sortOrder: 1 },
  { code: 'STANDARD', name: 'Standard', sortOrder: 2 },
  { code: 'PREMIUM', name: 'Premium', sortOrder: 3 },
  { code: 'LUXURY', name: 'Luxury', sortOrder: 4 },
  { code: 'CUSTOM', name: 'Custom', sortOrder: 5 },
] as const;

export const WASTAGE_RULES: Array<{ key: string; label: string; percent: number }> = [
  { key: 'cement', label: 'Cement', percent: 3 },
  { key: 'steel', label: 'Steel', percent: 5 },
  { key: 'brick', label: 'Brick', percent: 5 },
  { key: 'block', label: 'Block', percent: 3 },
  { key: 'tiles', label: 'Tiles', percent: 8 },
  { key: 'marble', label: 'Marble', percent: 10 },
  { key: 'granite', label: 'Granite', percent: 8 },
  { key: 'paint', label: 'Paint', percent: 8 },
  { key: 'electrical-wire', label: 'Electrical wire', percent: 10 },
  { key: 'pipe', label: 'Pipe', percent: 8 },
  { key: 'wood', label: 'Wood', percent: 12 },
  { key: 'plywood', label: 'Plywood', percent: 10 },
  { key: 'laminate', label: 'Laminate', percent: 12 },
  { key: 'glass', label: 'Glass', percent: 8 },
  { key: 'wallpaper', label: 'Wallpaper', percent: 10 },
];

export const RATE_SOURCE_REGISTRY = [
  {
    slug: 'cpwd-sor',
    name: 'CPWD Schedule of Rates',
    organization: 'Central Public Works Department',
    sourceType: 'OFFICIAL_SOR' as const,
    sourceUrl: 'https://cpwd.gov.in/',
    coverage: 'India (central works)',
    notes: 'Registry only. Do not seed numeric rates until a dated SOR extract is ingested.',
  },
  {
    slug: 'cpwd-analysis-of-rates',
    name: 'CPWD Analysis of Rates',
    organization: 'Central Public Works Department',
    sourceType: 'OFFICIAL_SOR' as const,
    sourceUrl: 'https://cpwd.gov.in/',
    coverage: 'India',
    notes: 'Coefficient / analysis document. Ingest coefficients separately from selling prices.',
  },
  {
    slug: 'varnarc-national-planning-baseline',
    name: 'Varnarc national planning baseline',
    organization: 'Varnarc',
    sourceType: 'ESTIMATED_FALLBACK' as const,
    sourceUrl: null,
    coverage: 'India (indicative)',
    notes:
      'Transparent fallback used when no official local rate is loaded. Never labelled official.',
  },
] as const;

export const COST_QUALITY_TO_TIER = {
  basic: 'ECONOMY',
  standard: 'STANDARD',
  premium: 'PREMIUM',
  luxury: 'LUXURY',
} as const;

export type QualitySpecificationLine = {
  categoryKey: string;
  specKey: string;
  label: string;
};

export const QUALITY_SPECIFICATIONS: Record<string, QualitySpecificationLine[]> = {
  ECONOMY: [
    { categoryKey: 'steel', specKey: 'fe415', label: 'TMT Fe415 (economy planning spec)' },
    { categoryKey: 'cement', specKey: 'opc-43', label: 'OPC 43 (economy planning spec)' },
    { categoryKey: 'flooring', specKey: 'ceramic', label: 'Ceramic flooring' },
    { categoryKey: 'paint', specKey: 'distemper', label: 'Distemper / economy emulsion' },
  ],
  STANDARD: [
    { categoryKey: 'steel', specKey: 'fe500d', label: 'TMT Fe500D' },
    { categoryKey: 'cement', specKey: 'opc-53', label: 'OPC 53' },
    { categoryKey: 'flooring', specKey: 'vitrified', label: 'Vitrified tiles' },
    { categoryKey: 'paint', specKey: 'acrylic-emulsion', label: 'Acrylic emulsion' },
  ],
  PREMIUM: [
    { categoryKey: 'steel', specKey: 'fe550d', label: 'TMT Fe550D (premium planning spec)' },
    { categoryKey: 'cement', specKey: 'opc-53', label: 'OPC 53 / PPC as specified' },
    { categoryKey: 'flooring', specKey: 'granite', label: 'Granite / large-format vitrified' },
    { categoryKey: 'paint', specKey: 'luxury-emulsion', label: 'Luxury emulsion' },
  ],
  LUXURY: [
    { categoryKey: 'steel', specKey: 'fe550d', label: 'TMT Fe550D / designer-specified' },
    { categoryKey: 'cement', specKey: 'opc-53', label: 'Specified cement + admixtures' },
    {
      categoryKey: 'flooring',
      specKey: 'imported-stone',
      label: 'Imported stone / engineered finish',
    },
    { categoryKey: 'paint', specKey: 'imported-paint', label: 'Specified luxury paint system' },
  ],
  CUSTOM: [],
};

export function qualitySpecificationsForCostQuality(
  quality: keyof typeof COST_QUALITY_TO_TIER,
): QualitySpecificationLine[] {
  return (
    QUALITY_SPECIFICATIONS[COST_QUALITY_TO_TIER[quality]] ?? QUALITY_SPECIFICATIONS.STANDARD ?? []
  );
}

export const DEFAULT_COMMERCIAL_RULES = [
  {
    kind: 'CONTINGENCY' as const,
    percent: 10,
    indexFactor: null as number | null,
    notes: 'Planning contingency on subtotal. Not a statutory levy.',
  },
  {
    kind: 'OVERHEAD' as const,
    percent: 8,
    indexFactor: null,
    notes: 'Contractor overhead planning allowance. Not applied as an official fee.',
  },
  {
    kind: 'PROFIT' as const,
    percent: 10,
    indexFactor: null,
    notes: 'Contractor profit planning allowance. Not a tender markup.',
  },
  {
    kind: 'TAX' as const,
    percent: 0,
    indexFactor: null,
    notes: 'GST/tax omitted until a jurisdiction is configured. Do not invent a rate.',
  },
  {
    kind: 'ESCALATION' as const,
    percent: null as number | null,
    indexFactor: 1,
    notes: 'Escalation index default 1.0 until a dated series is ingested.',
  },
];

export const WORK_ITEM_PLANNING_RESOURCES = [
  {
    workItemCode: 'BRICK_MASONRY',
    resourceType: 'MATERIAL' as const,
    resourceKey: 'brick',
    quantityCoefficient: 500,
    wastagePercent: 5,
    unit: 'nos',
    planningRate: 8,
  },
  {
    workItemCode: 'BRICK_MASONRY',
    resourceType: 'MATERIAL' as const,
    resourceKey: 'cement',
    quantityCoefficient: 0.076,
    wastagePercent: 3,
    unit: 'bag',
    planningRate: 380,
  },
  {
    workItemCode: 'BRICK_MASONRY',
    resourceType: 'LABOUR' as const,
    resourceKey: 'mason-grade-i',
    quantityCoefficient: 0.8,
    wastagePercent: 0,
    unit: 'day',
    planningRate: 900,
  },
  {
    workItemCode: 'INTERNAL_PLASTER',
    resourceType: 'MATERIAL' as const,
    resourceKey: 'cement',
    quantityCoefficient: 0.15,
    wastagePercent: 3,
    unit: 'bag',
    planningRate: 380,
  },
  {
    workItemCode: 'RCC_SLAB',
    resourceType: 'MATERIAL' as const,
    resourceKey: 'cement',
    quantityCoefficient: 6.5,
    wastagePercent: 3,
    unit: 'bag',
    planningRate: 380,
  },
  {
    workItemCode: 'RCC_SLAB',
    resourceType: 'MATERIAL' as const,
    resourceKey: 'steel',
    quantityCoefficient: 90,
    wastagePercent: 5,
    unit: 'kg',
    planningRate: 55,
  },
];

export const PRODUCTIVITY_NORMS = [
  {
    tradeSlug: 'mason-grade-i',
    workItemCode: 'BRICK_MASONRY',
    outputPerDay: 1.25,
    unit: 'cum',
    crewComposition: '1 mason + 1 helper (planning norm)',
  },
  {
    tradeSlug: 'mason-grade-i',
    workItemCode: 'INTERNAL_PLASTER',
    outputPerDay: 12,
    unit: 'sqm',
    crewComposition: '1 mason + 1 helper (planning norm)',
  },
  {
    tradeSlug: 'bar-bender',
    workItemCode: 'REINFORCEMENT',
    outputPerDay: 150,
    unit: 'kg',
    crewComposition: '1 bar bender + 1 helper (planning norm)',
  },
] as const;
