CREATE TABLE "cars" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "make" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "variant" TEXT NOT NULL DEFAULT '',
    "year_from" INTEGER,
    "year_to" INTEGER,
    "body_type" TEXT,
    "doors" INTEGER,
    "seats" INTEGER,
    "engine_code" TEXT,
    "engine_displacement" DECIMAL(14,4),
    "engine_cylinders" INTEGER,
    "engine_valves" INTEGER,
    "engine_fuel_type" TEXT,
    "engine_power_bhp" DECIMAL(14,4),
    "engine_power_kw" DECIMAL(14,4),
    "engine_torque_nm" DECIMAL(14,4),
    "engine_aspiration" TEXT,
    "engine_position" TEXT,
    "gearbox_type" TEXT,
    "gears" INTEGER,
    "drivetrain" TEXT,
    "acceleration_0_100" DECIMAL(14,4),
    "top_speed_kph" DECIMAL(14,4),
    "top_speed_mph" DECIMAL(14,4),
    "fuel_economy_combined_mpg" DECIMAL(14,4),
    "fuel_economy_combined_l100" DECIMAL(14,4),
    "fuel_economy_urban_l100" DECIMAL(14,4),
    "fuel_economy_extra_urban_l100" DECIMAL(14,4),
    "fuel_tank_litres" DECIMAL(14,4),
    "co2_gkm" DECIMAL(14,4),
    "emissions_standard" TEXT,
    "nox_mgkm" DECIMAL(14,4),
    "length_mm" DECIMAL(14,4),
    "width_mm" DECIMAL(14,4),
    "height_mm" DECIMAL(14,4),
    "wheelbase_mm" DECIMAL(14,4),
    "weight_kg" DECIMAL(14,4),
    "gross_weight_kg" DECIMAL(14,4),
    "boot_litres" DECIMAL(14,4),
    "boot_litres_max" DECIMAL(14,4),
    "tyre_front" TEXT,
    "tyre_rear" TEXT,
    "brake_front" TEXT,
    "brake_rear" TEXT,
    "battery_kwh" DECIMAL(14,4),
    "electric_range_km" DECIMAL(14,4),
    "charging_kw" DECIMAL(14,4),
    "source_file" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cars_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "cars_make_idx" ON "cars"("make");
CREATE INDEX "cars_make_model_idx" ON "cars"("make", "model");
CREATE INDEX "cars_engine_fuel_type_idx" ON "cars"("engine_fuel_type");
CREATE INDEX "cars_year_from_idx" ON "cars"("year_from");
