/** Re-export Schema.org JSON-LD builders from @varnarc/validation (compat shim). */
export {
  articleJsonLd,
  assertValidJsonLdGraph,
  assertValidJsonLdNode,
  breadcrumbJsonLd,
  buildAggregateRatingJsonLd,
  faqJsonLd,
  filterVisibleFaqs,
  howToJsonLd,
  itemListJsonLd,
  jsonLdAbsoluteUrl,
  jsonLdGraphTypes,
  localBusinessJsonLd,
  organizationJsonLd,
  productJsonLd,
  reviewJsonLd,
  softwareApplicationJsonLd,
  webApplicationJsonLd,
  webPageJsonLd,
  websiteJsonLd,
  type JsonLdAggregateRatingInput,
  type JsonLdBreadcrumbItem,
  type JsonLdFaqItem,
  type JsonLdHowToStep,
  type JsonLdListItem,
  type JsonLdObject,
} from '@varnarc/validation';
